"""your message

Revision ID: 6f6049c2c220
Revises: 1f1cc2b2494d
Create Date: 2024-10-02 17:28:14.735510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f6049c2c220"
down_revision: Union[str, None] = "1f1cc2b2494d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "star_wars_characters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("height", sa.String(), nullable=True),
        sa.Column("mass", sa.String(), nullable=True),
        sa.Column("force", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_orders_customeer_id", table_name="orders")
    op.drop_index("ix_orders_order_date", table_name="orders")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_friendships_friend_id", table_name="friendships")
    op.drop_index("ix_friendships_user_id", table_name="friendships")
    op.drop_table("friendships")
    op.drop_index("ix_documents_author_id", table_name="documents")
    op.drop_index(
        "ix_documents_content", table_name="documents", postgresql_using="gin"
    )
    op.drop_index("ix_documents_creation_date", table_name="documents")
    op.drop_index("ix_documents_title", table_name="documents")
    op.drop_table("documents")
    op.drop_table("documets")
    op.drop_index("ix_blog_posts_tags", table_name="blog_posts", postgresql_using="gin")
    op.drop_table("blog_posts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_posts",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="blog_posts_pkey"),
    )
    op.create_index(
        "ix_blog_posts_tags",
        "blog_posts",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "documets",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("creation_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="documets_pkey"),
    )
    op.create_table(
        "documents",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("creation_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="documents_pkey"),
    )
    op.create_index("ix_documents_title", "documents", ["title"], unique=False)
    op.create_index(
        "ix_documents_creation_date", "documents", ["creation_date"], unique=False
    )
    op.create_index(
        "ix_documents_content",
        "documents",
        [sa.text("to_tsvector('english'::regconfig, content)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_documents_author_id", "documents", ["author_id"], unique=False)
    op.create_table(
        "friendships",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("friend_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("since_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("user_id", "friend_id", name="friendships_pkey"),
    )
    op.create_index("ix_friendships_user_id", "friendships", ["user_id"], unique=False)
    op.create_index(
        "ix_friendships_friend_id", "friendships", ["friend_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=15), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="orders_pkey"),
    )
    op.create_index("ix_orders_status", "orders", ["status"], unique=False)
    op.create_index("ix_orders_order_date", "orders", ["order_date"], unique=False)
    op.create_index("ix_orders_customeer_id", "orders", ["customer_id"], unique=False)
    op.drop_table("star_wars_characters")
    # ### end Alembic commands ###
