"""your message

Revision ID: 6f6049c2c220
Revises: 1f1cc2b2494d
Create Date: 2024-10-02 17:28:14.735510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f6049c2c220"
down_revision: Union[str, None] = "1f1cc2b2494d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "star_wars_characters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("height", sa.String(), nullable=True),
        sa.Column("mass", sa.String(), nullable=True),
        sa.Column("force", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_orders_customeer_id", table_name="orders")
    op.drop_index("ix_orders_order_date", table_name="orders")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_friendships_friend_id", table_name="friendships")
    op.drop_index("ix_friendships_user_id", table_name="friendships")
    op.drop_table("friendships")
    op.drop_index("ix_documents_author_id", table_name="documents")
    op.drop_index(
        "ix_documents_content", table_name="documents", postgresql_using="gin"
    )
    op.drop_index("ix_documents_creation_date", table_name="documents")
    op.drop_index("ix_documents_title", table_name="documents")
    op.drop_table("documents")
    op.drop_table("documets")
    op.drop_index("ix_blog_posts_tags", table_name="blog_posts", postgresql_using="gin")
    op.drop_table("blog_posts")
    # ### end Alembic commands ###


def upgrade() -> None:
    pass
